HAI 1.3

I HAS A n ITZ 5040

IM IN YR loop UPPIN YR nop WILE...
    SUM OF SUM OF SUM OF SUM OF SUM OF...
        MOD OF n AN 11 AN...
        MOD OF n AN 13 AN...
        MOD OF n AN 14 AN...
        MOD OF n AN 17 AN...
        MOD OF n AN 19 AN...
        MOD OF n AN 20
    n R SUM OF n AN 5040
IM OUTTA YR loop

VISIBLE n
KTHXBYE
