HAI 1.3

I HAS A n ITZ 100
I HAS A sum ITZ PRODUKT OF SUM OF n AN 1 AN QUOSHUNT OF n AN 2
I HAS A sqsum ITZ PRODUKT OF sum AN sum
I HAS A sumsq ITZ 0

IM IN YR loop UPPIN YR i TIL BOTH SAEM i AN 101
    sumsq R SUM OF sumsq AN PRODUKT OF i AN i
IM OUTTA YR loop

VISIBLE DIFF OF sqsum AN sumsq

KTHXBYE
